from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.book import BookResponse

# ---------------------------------------------------------------------------
# Option A — Metadata enrichment
# ---------------------------------------------------------------------------


class EnrichRequest(BaseModel):
    title: str = Field(
        ...,
        min_length=1,
        description="Book title to enrich.",
        examples=["Dune"],
    )
    author: str = Field(
        ...,
        min_length=1,
        description="Primary author of the book.",
        examples=["Frank Herbert"],
    )
    description: str | None = Field(
        None,
        description="Optional synopsis or notes that help the AI generate richer metadata.",
        examples=["A science fiction epic set on the desert planet Arrakis."],
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "title": "Dune",
                "author": "Frank Herbert",
                "description": "A science fiction epic set on the desert planet Arrakis.",
            }
        }
    )


class EnrichResponse(BaseModel):
    summary: str = Field(
        ...,
        description=(
            "AI-generated one-paragraph summary of the book. "
            "When `source` is `fallback` this equals the provided description."
        ),
    )
    tags: list[str] = Field(
        ...,
        description="Suggested classification tags (genre, topic, era, …).",
    )
    keywords: list[str] = Field(
        ...,
        description="Key terms extracted from the title/author/description for search indexing.",
    )
    source: Literal["openai", "fallback"] = Field(
        ...,
        description=(
            "`openai` — result was generated by the configured OpenAI model. "
            "`fallback` — `OPENAI_API_KEY` is not set or an error occurred; "
            "deterministic heuristics were used instead."
        ),
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "summary": "A science fiction epic following Paul Atreides on the desert planet Arrakis, where control of the spice melange determines the fate of the universe.",
                "tags": ["science-fiction", "epic", "classic", "space-opera"],
                "keywords": ["dune", "arrakis", "spice", "paul", "atreides", "herbert"],
                "source": "openai",
            }
        }
    )


# ---------------------------------------------------------------------------
# Option B — Semantic search
# ---------------------------------------------------------------------------


class AISearchResponse(BaseModel):
    items: list[BookResponse] = Field(
        ...,
        description="Books ranked by semantic similarity to the query (most similar first).",
    )
    total: int = Field(..., description="Number of books returned.")
    source: Literal["openai", "fallback"] = Field(
        ...,
        description=(
            "`openai` — results ranked by cosine similarity of OpenAI embeddings. "
            "`fallback` — `OPENAI_API_KEY` is not set; ILIKE keyword search was used instead."
        ),
    )
    query: str = Field(..., description="The original query string that was searched.")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "items": [],
                "total": 3,
                "source": "openai",
                "query": "books about space exploration and survival",
            }
        }
    )


# ---------------------------------------------------------------------------
# Option C — Ask the Library
# ---------------------------------------------------------------------------


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="A natural-language question about the library collection.",
        examples=["Do you have any books about artificial intelligence?"],
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {"question": "Do you have any books about artificial intelligence?"}
        }
    )


class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description=(
            "Natural-language answer grounded **only** in books found in the database. "
            "The assistant never invents titles or authors."
        ),
    )
    books: list[BookResponse] = Field(
        ...,
        description=(
            "The actual database records used to formulate the answer. "
            "Always inspect this list to verify the answer is grounded."
        ),
    )
    source: Literal["openai", "fallback"] = Field(
        ...,
        description=(
            "`openai` — answer was generated by the configured OpenAI model. "
            "`fallback` — a pre-built template answer was returned without AI."
        ),
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "answer": "Yes! We have 2 books about artificial intelligence: 'Superintelligence' by Nick Bostrom and 'Life 3.0' by Max Tegmark.",
                "books": [],
                "source": "openai",
            }
        }
    )
